-- Migration: Add missing SEO and Package columns if not present
-- Compatible with MySQL 5.7+ / 8.0+ / MariaDB / Hostinger phpMyAdmin

-- 1. Upgrade Blogs Table
ALTER TABLE `blogs` ADD COLUMN IF NOT EXISTS `meta_title` VARCHAR(150) DEFAULT NULL;
ALTER TABLE `blogs` ADD COLUMN IF NOT EXISTS `meta_description` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `blogs` ADD COLUMN IF NOT EXISTS `focus_keyphrase` VARCHAR(150) DEFAULT NULL;
ALTER TABLE `blogs` ADD COLUMN IF NOT EXISTS `excerpt` TEXT DEFAULT NULL;
ALTER TABLE `blogs` ADD COLUMN IF NOT EXISTS `image_alt` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `blogs` ADD COLUMN IF NOT EXISTS `tags` TEXT DEFAULT NULL;

-- 2. Upgrade Treks Table
ALTER TABLE `treks` ADD COLUMN IF NOT EXISTS `meta_title` VARCHAR(150) DEFAULT NULL;
ALTER TABLE `treks` ADD COLUMN IF NOT EXISTS `meta_description` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `treks` ADD COLUMN IF NOT EXISTS `focus_keyphrase` VARCHAR(150) DEFAULT NULL;
ALTER TABLE `treks` ADD COLUMN IF NOT EXISTS `excerpt` TEXT DEFAULT NULL;
ALTER TABLE `treks` ADD COLUMN IF NOT EXISTS `image_alt` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `treks` ADD COLUMN IF NOT EXISTS `tags` TEXT DEFAULT NULL;
